[package]
name = "extism-manifest"
version = "0.0.1-alpha"
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/extism/extism"
description = "Extism plug-in manifest crate"

[dependencies]
serde = {version = "1", features=["derive"]}
base64 = "0.20.0-alpha"